name: Publish Unit Test Results
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
uses: EnricoMi/publish-unit-test-result-action/composite@v1
if: always()
with:
  files: test-results/**/*.xml