name: Publish Unit Test Results
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: windows-latest
    steps:
      # Execute unit tests
      - name: Unit Test
        run: mvn clean test